// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
    public static final int NUM_OF_ARGS = 1;
	public static void main(String[]  args) {
        if (args.length != NUM_OF_ARGS) {
            System.err.println("Usage: java TimeRandom <NUMBER_OF_RUNS>");
            return;
        }

        int numRuns = Integer.parseInt(args[0]);
        int greaterThanHalfCounter = 0;
        int lessEqualThanHalfCounter = 0;

        for (int i = 0; i < numRuns; i++) {
            double randomNumber = Math.random();
            if (randomNumber > 0.5)
            {
                greaterThanHalfCounter++;
            }
            else {
                lessEqualThanHalfCounter++;
            }
        }
        System.out.println("> 0.5: " + greaterThanHalfCounter + " times");
        System.out.println("<= 0.5: " + lessEqualThanHalfCounter + " times");
        if (greaterThanHalfCounter < lessEqualThanHalfCounter) {
            System.out.println("Ratio: " + (double)greaterThanHalfCounter / (double)lessEqualThanHalfCounter);
        }
	}


}
